
# Properties for saucedemo.com
username=standard_user
password=secret_sauce

wrong_username=invalid_user
wrong_password=invalid_pass

locked_username=locked_out_user

baseUrl=https://www.saucedemo.com
